### ISSUE TITLE
Ability to install without using composer or vagrant?

### ISSUE THREAD

**Issue by SBBH** [Minds-On-Design-Lab/giving-impact#3]
Is this possible? I'd rather not install these and just do a normal manual config and setup.

**Comment by sg-modlab** [comment]
Thank you for reaching out. Vagrant is not is required, it was just included as an option. Please see the manual install option details in the readme for the non-vagrant option. 

Composer, however, is required but can be [installed locally](https://getcomposer.org/doc/00-intro.md) to run in your project folder.
